name: Test Workflow

on: push

jobs:
  diff1:
    if: github.ref == refs/heads/try_workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying with branch ${{ github.ref }}'
  diff2:
    if: $GITHUB_REF == refs/heads/try_workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying with branch $GITHUB_REF"
  print_all:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: echo '${{ toJson(env) }}'
      - name: Print vars
        run: echo '${{ toJson(vars) }}'
      - name: Print github
        run: echo '${{ toJson(github) }}'
      - name: Print runner
        run: echo '${{ toJson(runner) }}'
