name: Test Workflow

on: push

jobs:
  print_job:
    runs-on: ubuntu-latest
    steps:
      - id: print_env
        run: echo ${{ toJson(env) }}
      - id: print_vars
        run: echo ${{ toJson(vars) }}
      - id: print_github
        run: echo ${{ toJson(github) }}
      - id: print_runner
        run: echo ${{ toJson(runner) }}
