name: Test Workflow

on: push

jobs:
  dump_contexts:
    runs-on: ubuntu-latest
    env:
      GITHUB_CTX: $${{ toJson(github) }}
      JOB_CTX: $${{ toJson(job) }}
      STEPS_CTX: $${{ toJson(steps) }}
      RUNNER_CTX: $${{ toJson(runner) }}
      STRATEGY_CTX: $${{ toJson(strategy) }}
      MATRIX_CTX: $${{ toJson(matrix) }}
    steps:
      - name: github
        run: echo "$GITHUB_CTX"
      - name: job
        run: echo "$JOB_CTX"
      - name: steps
        run: echo "$STEPS_CTX"
      - name: runner
        run: echo "$RUNNER_CTX"
      - name: strategy
        run: echo "$STRATEGY_CTX"
      - name: matrix
        run: echo "$MATRIX_CTX"
